apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sayurbox.fullname" . }}

  labels:

    {{- include "sayurbox.labels" . | nindent 4 }}

spec:

  {{- if not .Values.autoscaling.enabled }}

  replicas: {{ .Values.replicaCount }}

  {{- end }}

  strategy:

    type: {{.Values.updateStrategy.type }}

  selector:

    matchLabels:

      {{- include "sayurbox.selectorLabels" . | nindent 6 }}

  template:

    metadata:

      {{- with .Values.podAnnotations }}

     annotations:

        {{- toYaml . | nindent 8 }}

      {{- end }}

      labels:

        {{- include "sayurbox.selectorLabels" . | nindent 8 }}

    spec:

      {{- with .Values.imagePullSecrets }}

      imagePullSecrets:

        {{- toYaml . | nindent 8 }}

      {{- end }}

      serviceAccountName: {{ include "sayurbox.serviceAccountName" . }}

      securityContext:

        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      containers:

        - name: {{ .Chart.Name }}

          securityContext:

            {{- toYaml .Values.securityContext | nindent 12 }}

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:

            - name: http

              containerPort: 80

              protocol: TCP

          livenessProbe:

            httpGet:

              path: {{ .Values.livenessProbe.path }}

              port: {{ .Values.livenessProbe.port }}

              httpHeaders:

            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds}}

            periodSeconds: {{ .Values.livenessProbe.periodSeconds}}

          readinessProbe:

            httpGet:

              path: {{ .Values.readinessProbe.path }}

              port: {{ .Values.readinessProbe.port }}

            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds}}

            periodSeconds: {{ .Values.readinessProbe.periodSeconds}}

         envFrom:

            - configMapRef:

               name: {{ include "sayurbox.fullname" . }}

          resources:

            requests:

              memory: {{ .Values.resources.requests.memory }}

              cpu: {{ .Values.resources.requests.cpu }}

            limits:

              memory: {{ .Values.resources.limits.memory }}

              cpu: {{ .Values.resources.limits.cpu }}

      {{- with .Values.nodeSelector }}

      nodeSelector:

        {{- toYaml . | nindent 8 }}

      {{- end }}

      affinity:

       nodeAffinity:

         requiredDuringSchedulingIgnoredDuringExecution:

            nodeSelectorTerms:

            - matchExpressions:

              - key: {{ .Values.affinity.app }}

                operator: In

                values:

                - {{ .Values.affinity.appb }}

              - key: {{ .Values.affinity.db }}

                operator: In

                values:

                - {{ .Values.affinity.dbb }}

              - key: {{ .Values.affinity.monitoring }}

                operator: In

                values:

                - {{ .Values.affinity.monitoringb }}