apiVersion: policy/v1

kind: PodDisruptionBudget

metadata:

    name: {{ include "sayurbox.fullname" . }}

    labels:

    {{- include "sayurbox.labels" . | nindent 4 }}

spec:

    selector:

      matchLabels:

        app.kubernetes.io/name: {{ include "sayurbox.fullname" . }}

        app.kubernetes.io/instance: {{ .Release.Name }}

    minAvailable: {{ .Values.autoscaling.pdbMinAvailable }}