{{- if .Values.serviceAccount.create -}}

apiVersion: v1

kind: ServiceAccount

metadata:

  name: {{ include "sayurbox.serviceAccountName" . }}

  labels:

    {{- include "sayurbox.labels" . | nindent 4 }}

  {{- with .Values.serviceAccount.annotations }}

  annotations:

    {{- toYaml . | nindent 4 }}

  {{- end }}

{{- end }}


