apiVersion: v1

kind: Service

metadata:

  name: {{ include "sayurbox.fullname" . }}

  labels:

    {{- include "sayurbox.labels" . | nindent 4 }}

spec:

  type: {{ .Values.service.type }}

  ports:

    - port: {{ .Values.service.port }}

      targetPort: http

      protocol: TCP

      name: http

  selector:

    {{- include "sayurbox.selectorLabels" . | nindent 4 }}

status:

  loadBalancer: {}